"""
config.py

Central configuration module for the Web Application Security Scanner.

This file contains NO business logic. It only centralizes constant
values (paths, timeouts, defaults, feature flags) that are consumed
by every other module in the project (crawler, detectors, reports,
external tool wrappers, LLM integration, logging, etc.).

Design rules followed in this file:
  - Every value lives here once. No module should hardcode a timeout,
    a path, a default header, a payload count, etc. If a module needs
    a value, it imports it from here.
  - Constants are UPPERCASE.
  - Values are grouped into clearly commented sections.
  - Directory values are pathlib.Path objects so every consumer can
    use them the same way (os.path.join is not needed anywhere else
    in the project).
  - Nothing here talks to the network, the filesystem (beyond
    creating output folders), or any external tool. Pure data.

Python 3.10+
"""

from __future__ import annotations

import os
from pathlib import Path

# ======================================================================
# 1. APPLICATION INFORMATION
# ======================================================================
# General identity of the tool. Used mainly for CLI banners, the PDF
# report header/footer, log file headers, and --version output.

APP_NAME = "WebScan"
# Used by: main.py (CLI banner), reports/pdf_generator.py,
#          reports/html_generator.py, utils/logger.py (log header)
# Reason: Human-readable product name shown to the user and printed
#         in the generated report.
# User configurable: Yes (rename the tool for your own build)

APP_VERSION = "0.1.0"
# Used by: main.py (--version flag), reports/pdf_generator.py
#          (footer "Generated by WebScan v0.1.0")
# Reason: Traceability. A pentest report should always state which
#         tool/version produced the findings.
# User configurable: Yes, but should be bumped manually per release,
#         not edited casually.

APP_AUTHOR = "Bourdaoui Lina"
# Used by: reports/pdf_generator.py, reports/html_generator.py
# Reason: Displayed in the report metadata / cover page.
# User configurable: Yes

APP_DESCRIPTION = (
    "Modular web application security scanner: recon, crawling, "
    "input discovery, vulnerability checks and reporting."
)
# Used by: main.py (argparse description), README generation if any
# Reason: Short summary shown in --help and report cover page.
# User configurable: Yes

DEBUG_MODE = False
# Used by: main.py, utils/logger.py, scanner/scan_manager.py
# Reason: Global switch. When True, stack traces are printed in full,
#         log level is forced to DEBUG, and raw tool output is kept
#         instead of being cleaned up.
# User configurable: Yes (normally via --debug CLI flag, not by
#         hand-editing this file)


# ======================================================================
# 2. DIRECTORY LAYOUT
# ======================================================================
# Every path in the project is derived from BASE_DIR so the tool can
# be moved/copied anywhere without breaking. No module should build
# a path with a raw string; import the Path object it needs from here.

BASE_DIR = Path(__file__).resolve().parent
# Used by: every path constant below
# Reason: Anchor point for all other paths. Using the file's own
#         location (not os.getcwd()) means the tool works correctly
#         no matter which directory it is launched from.
# User configurable: No

# --- Output (results produced by a scan run) -------------------------
OUTPUT_DIR = BASE_DIR / "output"
REPORTS_DIR = OUTPUT_DIR / "reports"
RAW_RESULTS_DIR = OUTPUT_DIR / "raw_results"
SCREENSHOTS_DIR = OUTPUT_DIR / "screenshots"
# Used by: reports/pdf_generator.py, reports/html_generator.py
#          (REPORTS_DIR), every module in modules/ that dumps raw
#          tool output or JSON findings (RAW_RESULTS_DIR),
#          modules/web/screenshot.py if implemented (SCREENSHOTS_DIR)
# Reason: Separates final deliverables (reports) from intermediate
#         evidence (raw tool output, screenshots) so the report
#         folder stays clean and shareable on its own.
# User configurable: Yes (e.g. point RAW_RESULTS_DIR to a scratch
#         disk on a low-storage VM)

LOGS_DIR = BASE_DIR / "logs"
# Used by: utils/logger.py
# Reason: Location for the rotating log file(s) of the scanner itself
#         (not the scan findings, the tool's own execution log).
# User configurable: Yes

# --- Assets (shipped with the tool, read-only at runtime) ------------
ASSETS_DIR = BASE_DIR / "assets"
PAYLOADS_DIR = ASSETS_DIR / "payloads"
WORDLISTS_DIR = ASSETS_DIR / "wordlists"
ICONS_DIR = ASSETS_DIR / "icons"
LOGO_PATH = ASSETS_DIR / "logo" / "logo.png"
# Used by: modules/analysis/sqli_detector.py, xss_detector.py
#          (PAYLOADS_DIR), modules/recon/gobuster_scanner.py
#          (WORDLISTS_DIR), reports/pdf_generator.py,
#          reports/html_generator.py (ICONS_DIR, LOGO_PATH for
#          branding the report)
# Reason: Keeps static data (payload lists, wordlists, branding
#         images) out of the code and easy to edit/extend without
#         touching any .py file.
# User configurable: Yes (drop your own wordlists/payload files here)

TEMPLATES_DIR = BASE_DIR / "templates"
# Used by: reports/html_generator.py
# Reason: Jinja2 (or similar) templates used to render the HTML
#         report, which is itself converted to PDF. Keeping templates
#         as files (not strings in code) makes the report's visual
#         design editable without touching Python.
# User configurable: Yes

# Directories that must exist before a scan starts. main.py should
# create any of these that are missing at startup.
REQUIRED_DIRECTORIES = (
    OUTPUT_DIR,
    REPORTS_DIR,
    RAW_RESULTS_DIR,
    SCREENSHOTS_DIR,
    LOGS_DIR,
)
# Used by: main.py (startup routine, e.g. for d in REQUIRED_DIRECTORIES:
#          d.mkdir(parents=True, exist_ok=True))
# Reason: Single source of truth for "what folders must exist", so
#         adding a new output subfolder later means editing this
#         tuple once instead of hunting for os.makedirs calls.
# User configurable: No (derived from the paths above)


# ======================================================================
# 3. HTTP REQUEST CONFIGURATION
# ======================================================================
# Shared defaults for every outgoing HTTP request the scanner makes,
# whether from the crawler or from a vulnerability detector.

REQUEST_TIMEOUT = 10
# Used by: modules/web/crawler.py, modules/analysis/sqli_detector.py,
#          xss_detector.py, csrf_checker.py, headers_checker.py,
#          utils/session_manager.py
# Reason: Maximum time (seconds) to wait for a single HTTP response
#         before giving up. Prevents the scan from hanging forever on
#         an unresponsive endpoint.
# User configurable: Yes

REQUEST_TIMEOUT_BLIND_SQLI = 15
# Used by: modules/analysis/sqli_detector.py (time-based blind SQLi
#          checks, e.g. SLEEP()-based payloads)
# Reason: Time-based blind injection payloads deliberately make the
#         server sleep. A timeout tuned for normal requests would
#         false-negative these checks, so a separate, higher timeout
#         is needed specifically for this technique.
# User configurable: Yes

MAX_RETRIES = 2
# Used by: modules/web/crawler.py, all modules/analysis/* detectors
# Reason: Number of times to retry a request after a network error
#         (timeout, connection reset) before marking that request as
#         failed and moving on. Avoids one flaky request stalling the
#         whole scan.
# User configurable: Yes

RETRY_BACKOFF_SECONDS = 1.5
# Used by: same modules as MAX_RETRIES
# Reason: Delay between retry attempts, to avoid hammering an
#         already-struggling server.
# User configurable: Yes

USER_AGENT = f"{APP_NAME}/{APP_VERSION} (+security-research)"
# Used by: modules/web/crawler.py, all modules/analysis/* detectors,
#          modules/recon/* (where applicable)
# Reason: Identifies the scanner's traffic in the target's access
#         logs. Useful for authorized testing (the client can filter
#         scanner traffic) and for basic honesty about automated
#         traffic.
# User configurable: Yes

DEFAULT_HEADERS = {
    "User-Agent": USER_AGENT,
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
}
# Used by: modules/web/crawler.py, utils/session_manager.py
# Reason: Baseline headers attached to every request so the scanner
#         behaves like a normal browser request rather than an
#         obviously bare HTTP client, which reduces trivial WAF
#         false blocks and gives more representative responses.
# User configurable: Yes

VERIFY_SSL = True
# Used by: modules/web/crawler.py, all modules/analysis/* detectors,
#          utils/session_manager.py
# Reason: Whether to validate TLS certificates. Set to False only
#         when intentionally testing an internal target with a
#         self-signed certificate (e.g. DVWA/Juice Shop in a lab VM).
# User configurable: Yes (should default to True; flip via CLI flag
#         for lab targets, not by editing this file permanently)

FOLLOW_REDIRECTS = True
MAX_REDIRECTS = 5
# Used by: modules/web/crawler.py, modules/analysis/* detectors
# Reason: Controls whether/how far the HTTP client follows 3xx
#         redirects. Capping MAX_REDIRECTS avoids redirect loops
#         consuming scan time.
# User configurable: Yes

PROXY = None
# Example: {"http": "http://127.0.0.1:8080", "https": "http://127.0.0.1:8080"}
# Used by: modules/web/crawler.py, all modules/analysis/* detectors
# Reason: Lets every request be routed through an intercepting proxy
#         (Burp Suite, mitmproxy) for manual inspection/debugging of
#         the scanner's own traffic during development.
# User configurable: Yes


# ======================================================================
# 4. SCOPE CONFIGURATION
# ======================================================================
# Default safety rails so the crawler cannot wander outside the
# authorized target or trigger destructive actions. utils/scope.py
# is expected to enforce these against the concrete target at runtime.

STRICT_SCOPE = True
# Used by: utils/scope.py, modules/web/crawler.py
# Reason: When True, the crawler only follows links whose domain
#         exactly matches (or is a subdomain of) the authorized
#         target. This is a safety control, not just a feature: an
#         unscoped crawler can end up sending payloads to third-party
#         sites linked from the target.
# User configurable: Yes, but should stay True by default for safety

EXCLUDED_URL_PATTERNS = (
    "logout",
    "signout",
    "delete",
    "remove",
    "unsubscribe",
)
# Used by: utils/scope.py, modules/web/crawler.py
# Reason: Substrings checked against a URL/form action before the
#         crawler follows it or a detector fuzzes it. Prevents the
#         scanner from accidentally logging itself out mid-scan or
#         triggering destructive/irreversible actions on the target.
# User configurable: Yes (add project-specific dangerous endpoints)

EXCLUDED_FILE_EXTENSIONS = (
    ".jpg", ".jpeg", ".png", ".gif", ".svg", ".ico", ".css",
    ".woff", ".woff2", ".ttf", ".eot", ".mp4", ".mp3", ".pdf", ".zip",
)
# Used by: modules/web/crawler.py
# Reason: Skips binary/static assets that cannot contain injectable
#         parameters or forms, saving scan time and log noise.
# User configurable: Yes

SCAN_DELAY_BETWEEN_REQUESTS = 0.5
# Used by: modules/web/crawler.py, modules/analysis/* detectors
# Reason: Waits a short amount of time between consecutive HTTP requests
#         to avoid overwhelming the target server. Makes the scanner
#         behave more politely during authorized assessments and reduces
#         the risk of triggering rate limits or WAF protections.
# User configurable: Yes

# ======================================================================
# 5. WEB CRAWLER CONFIGURATION
# ======================================================================

CRAWL_MAX_DEPTH = 3
# Used by: modules/web/crawler.py
# Reason: Maximum number of link "hops" from the starting URL. Caps
#         crawl time on large sites and avoids near-infinite crawls
#         on sites with dynamically generated links.
# User configurable: Yes

CRAWL_MAX_PAGES = 200
# Used by: modules/web/crawler.py
# Reason: Hard ceiling on total pages visited in one scan, independent
#         of depth (protects against very wide sitemaps). Acts as a
#         circuit breaker for the whole crawl phase.
# User configurable: Yes

CRAWL_CONCURRENCY = 5
# Used by: modules/web/crawler.py
# Reason: Number of concurrent requests the crawler is allowed to
#         make. Balances scan speed against not overloading the
#         target (important for a lab VM with limited resources).
# User configurable: Yes

CRAWL_DELAY_SECONDS = 0.0
# Used by: modules/web/crawler.py
# Reason: Optional fixed delay between requests, for intentionally
#         slow/stealthy crawling or to avoid tripping rate limiting
#         on the target during testing.
# User configurable: Yes

RESPECT_ROBOTS_TXT = False
# Used by: modules/web/crawler.py
# Reason: robots.txt expresses crawler etiquette for search engines,
#         not authorization for a security scan. Kept as an explicit,
#         visible flag (default False) so the choice is a conscious,
#         documented one rather than silently ignored.
# User configurable: Yes

CRAWL_SEED_PATHS = ("/", "/sitemap.xml", "/robots.txt")
# Used by: modules/web/crawler.py
# Reason: Starting points added to the crawl queue in addition to the
#         user-supplied target URL, to seed discovery from common
#         entry points.
# User configurable: Yes


# ======================================================================
# 6. FUZZING / VULNERABILITY DETECTION CONFIGURATION
# ======================================================================

SQLI_PAYLOADS_FILE = PAYLOADS_DIR / "sqli.txt"
XSS_PAYLOADS_FILE = PAYLOADS_DIR / "xss.txt"
CSRF_TOKEN_FIELD_NAMES = (
    "csrf_token", "csrfmiddlewaretoken", "authenticity_token",
    "_token", "__requestverificationtoken",
)
# Used by: modules/analysis/sqli_detector.py, xss_detector.py,
#          csrf_checker.py
# Reason: SQLI_PAYLOADS_FILE / XSS_PAYLOADS_FILE point to the editable
#         payload lists in assets/payloads/ so new payloads can be
#         added without touching detector code.
#         CSRF_TOKEN_FIELD_NAMES is the set of common form field names
#         csrf_checker.py looks for to decide whether a form is
#         CSRF-protected at all.
# User configurable: Yes

MAX_PAYLOADS_PER_PARAMETER = 25
# Used by: modules/analysis/sqli_detector.py, xss_detector.py
# Reason: Caps how many payloads are tried per discovered parameter.
#         Keeps scan time predictable on forms with many fields;
#         full payload lists can be large.
# User configurable: Yes

FUZZ_CONCURRENCY = 3
# Used by: modules/analysis/sqli_detector.py, xss_detector.py,
#          csrf_checker.py
# Reason: Separate (lower than CRAWL_CONCURRENCY) concurrency for
#         active testing requests, since these are more likely to
#         trigger WAF rate-limiting or affect application state.
# User configurable: Yes

SQLI_RESPONSE_TIME_THRESHOLD = 5.0
# Used by: modules/analysis/sqli_detector.py
# Reason: Minimum response delay (seconds) above the baseline request
#         time before a time-based blind SQLi payload is considered a
#         positive signal. Reduces false positives from normal
#         network jitter.
# User configurable: Yes

SQLI_ERROR_SIGNATURES_FILE = PAYLOADS_DIR / "sql_error_signatures.txt"
# Used by: modules/analysis/sqli_detector.py
# Reason: File of known SQL error strings (MySQL, PostgreSQL, MSSQL,
#         Oracle, SQLite) used for error-based detection. Kept as
#         data, not a hardcoded list in the detector, so new DBMS
#         signatures can be added easily.
# User configurable: Yes

XSS_CONFIRM_VIA_UNIQUE_MARKER = True
XSS_MARKER_PREFIX = "wsxss"
# Used by: modules/analysis/xss_detector.py
# Reason: Each XSS payload is wrapped with a unique marker string so
#         the detector can confirm the payload was reflected
#         unescaped (vs. coincidentally similar page content),
#         reducing false positives.
# User configurable: Yes


# ======================================================================
# 7. HTTP SECURITY HEADERS CONFIGURATION
# ======================================================================

REQUIRED_SECURITY_HEADERS = (
    "Content-Security-Policy",
    "Strict-Transport-Security",
    "X-Content-Type-Options",
    "X-Frame-Options",
    "Referrer-Policy",
    "Permissions-Policy",
)
# Used by: modules/analysis/headers_checker.py
# Reason: List of headers checked for presence/misconfiguration on
#         every crawled response. Centralized so the check list can
#         be extended (e.g. adding Cross-Origin-Opener-Policy) without
#         touching detector logic.
# User configurable: Yes


# ======================================================================
# 8. SEVERITY / CONFIDENCE SCALE
# ======================================================================
# Single source of truth for how findings are ranked, so detectors,
# scan_manager, and the report generators all agree on the same
# scale and the same display order/colors.

SEVERITY_LEVELS = ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO")
# Used by: models/finding.py, scanner/scan_manager.py (sorting
#          findings), reports/pdf_generator.py, html_generator.py
# Reason: Fixed, ordered vocabulary for finding severity. Keeping it
#         as a tuple (not free text) forces every detector to pick
#         from a known set, which the report can then reliably sort
#         and count.
# User configurable: No (changing this affects every module; only
#         change deliberately, not per scan)

SEVERITY_COLORS = {
    "CRITICAL": "#8B0000",
    "HIGH": "#D9534F",
    "MEDIUM": "#F0AD4E",
    "LOW": "#5BC0DE",
    "INFO": "#777777",
}
# Used by: reports/pdf_generator.py, reports/html_generator.py
# Reason: Consistent color coding for severity badges in the report,
#         defined once instead of in every template/report function.
# User configurable: Yes (rebrand report colors)

CONFIDENCE_LEVELS = ("CONFIRMED", "PROBABLE", "SUSPECTED")
# Used by: models/finding.py, modules/analysis/* detectors,
#          reports/pdf_generator.py, html_generator.py
# Reason: Separate from severity: severity is "how bad if true",
#         confidence is "how sure we are it's true". Reporting both
#         avoids drowning real findings in unverified noise.
# User configurable: No (fixed vocabulary, same reasoning as
#         SEVERITY_LEVELS)


# ======================================================================
# 9. REPORT GENERATION CONFIGURATION
# ======================================================================

REPORT_DEFAULT_TITLE = "Web Application Security Assessment Report"
REPORT_DATE_FORMAT = "%Y-%m-%d %H:%M"
REPORT_LANGUAGE = "en"
# Used by: reports/pdf_generator.py, reports/html_generator.py
# Reason: Cover page title, timestamp formatting used throughout the
#         report, and language tag (useful if you later add French
#         report templates alongside English ones).
# User configurable: Yes

REPORT_OUTPUT_FORMATS = ("pdf", "html", "json")
# Used by: scanner/scan_manager.py (decides what to generate at the
#          end of a run), reports/pdf_generator.py,
#          reports/html_generator.py
# Reason: Which report formats to produce by default. JSON is kept
#         as a machine-readable dump of the same findings, useful for
#         diffing between scans or feeding another tool.
# User configurable: Yes

PDF_PAGE_SIZE = "A4"
PDF_INCLUDE_TABLE_OF_CONTENTS = True
PDF_INCLUDE_RAW_TOOL_OUTPUT_APPENDIX = True
# Used by: reports/pdf_generator.py
# Reason: PDF_PAGE_SIZE for layout consistency; the two INCLUDE flags
#         let the report stay concise for executives while still
#         offering the appendix of raw evidence for a technical
#         reviewer.
# User configurable: Yes

REPORT_INCLUDE_SCREENSHOTS = False
# Used by: reports/pdf_generator.py, reports/html_generator.py,
#          modules/web/screenshot.py (if/when implemented)
# Reason: Screenshot capture requires a headless browser dependency
#         (e.g. Playwright). Off by default so the tool has no hard
#         dependency on a browser engine unless the user opts in.
# User configurable: Yes


# ======================================================================
# 10. LOGGING CONFIGURATION
# ======================================================================

LOG_LEVEL = "DEBUG" if DEBUG_MODE else "INFO"
# Used by: utils/logger.py
# Reason: Controls verbosity of the scanner's own execution log
#         (distinct from scan findings). Tied to DEBUG_MODE so one
#         flag controls both.
# User configurable: Yes (usually via DEBUG_MODE rather than directly)

LOG_FORMAT = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
# Used by: utils/logger.py
# Reason: Consistent log line format across every module that logs.
# User configurable: Yes

LOG_FILE = LOGS_DIR / "webscan.log"
LOG_TO_CONSOLE = True
LOG_MAX_BYTES = 5 * 1024 * 1024
LOG_BACKUP_COUNT = 3
# Used by: utils/logger.py
# Reason: LOG_FILE is the rotating log destination; LOG_TO_CONSOLE
#         controls whether logs are also echoed to stdout (useful
#         interactively, noisy in CI); LOG_MAX_BYTES/LOG_BACKUP_COUNT
#         configure log rotation so logs/ doesn't grow unbounded over
#         repeated scans.
# User configurable: Yes


# ======================================================================
# 11. EXTERNAL TOOLS CONFIGURATION
# ======================================================================
# Wrappers around system binaries. Paths default to "just the command
# name" so the tool works as long as the binary is on PATH (true by
# default on Kali); override with an absolute path if needed.

TOOLS_ENABLED = {
    "nmap": True,
    "gobuster": True,
}
# Used by: scanner/scan_manager.py (decides which recon modules to
#          run), utils/tool_checker.py (which binaries to verify at
#          startup)
# Reason: Per-tool on/off switch, independent of whether the binary
#         is installed. Lets a user disable nmap entirely (per the
#         "is nmap still worth it" discussion) without touching code.
# User configurable: Yes

TOOL_BINARIES = {
    "nmap": os.environ.get("WEBSCAN_NMAP_PATH", "nmap"),
    "gobuster": os.environ.get("WEBSCAN_GOBUSTER_PATH", "gobuster"),
}
# Used by: utils/tool_checker.py, utils/subprocess_runner.py,
#          modules/recon/nmap_scanner.py, gobuster_scanner.py
# Reason: Command/path used to invoke each external tool. Reads from
#         an environment variable first so CI or a non-standard
#         install doesn't require editing this file.
# User configurable: Yes

TOOL_TIMEOUT_SECONDS = 300
# Used by: utils/subprocess_runner.py
# Reason: Hard ceiling on how long any single external tool subprocess
#         is allowed to run before being killed. Prevents e.g. a
#         misconfigured nmap scan from hanging the whole tool run.
# User configurable: Yes

NMAP_DEFAULT_ARGS = ["-sV", "-p", "80,443", "--open"]
# Used by: modules/recon/nmap_scanner.py
# Reason: Default nmap invocation, deliberately narrow (quick
#         service-version check on web ports) rather than a full
#         port sweep, matching the project's decision to keep nmap
#         as a lightweight optional pre-check, not a full network
#         scan module.
# User configurable: Yes

GOBUSTER_DEFAULT_WORDLIST = WORDLISTS_DIR / "common.txt"
GOBUSTER_DEFAULT_EXTENSIONS = ("php", "html", "js", "txt", "bak")
GOBUSTER_THREADS = 20
# Used by: modules/recon/gobuster_scanner.py
# Reason: Default wordlist/extensions/thread count for directory and
#         file discovery. Centralized so a user can point to a bigger
#         wordlist (e.g. SecLists) by changing one path.
# User configurable: Yes


# ======================================================================
# 12. SESSION / AUTHENTICATION CONFIGURATION
# ======================================================================
# Placeholders for utils/session_manager.py. No credentials are
# stored here; this only configures how the session manager behaves.
# Actual credentials should come from CLI args or environment
# variables, never hardcoded in this file or committed to source
# control.

AUTH_ENABLED = False
# Used by: utils/session_manager.py, modules/web/crawler.py,
#          modules/analysis/* detectors
# Reason: Global switch for authenticated scanning. When False, the
#         scanner runs entirely unauthenticated, which is the safest
#         default for a first run against an unfamiliar target.
# User configurable: Yes

AUTH_LOGIN_URL = None
AUTH_USERNAME_FIELD = "username"
AUTH_PASSWORD_FIELD = "password"
AUTH_USERNAME_ENV_VAR = "WEBSCAN_AUTH_USERNAME"
AUTH_PASSWORD_ENV_VAR = "WEBSCAN_AUTH_PASSWORD"
# Used by: utils/session_manager.py
# Reason: AUTH_LOGIN_URL is the target's login endpoint; the FIELD
#         constants name the form fields to fill; credentials
#         themselves are read from environment variables at runtime
#         (never stored as plain constants) to avoid accidentally
#         committing credentials to version control.
# User configurable: Yes

SESSION_COOKIE_PERSIST_FILE = OUTPUT_DIR / "session_cookies.json"
# Used by: utils/session_manager.py
# Reason: Where to persist the authenticated session's cookies across
#         the crawl and the various detector modules, so login only
#         happens once per scan run.
# User configurable: Yes


# ======================================================================
# 13. AI / LLM CONFIGURATION (disabled by default)
# ======================================================================
# Post-scan report writing only. The LLM is never given raw,
# unstructured data and never decides severity/confidence; it only
# rewrites already-structured Finding objects into readable prose.
# See models/finding.py for the structured data it will consume.

AI_ENABLED = False
# Used by: scanner/scan_manager.py, reports/pdf_generator.py,
#          reports/html_generator.py
# Reason: Off by default so the tool is fully usable (and fully
#         deterministic) with zero external API dependency. Report
#         generation must have a non-AI fallback path regardless of
#         this flag.
# User configurable: Yes

AI_PROVIDER = "anthropic"
AI_MODEL = "claude-sonnet-4-6"
# Used by: reports/pdf_generator.py or a future
#          modules/ai/report_writer.py
# Reason: Which LLM provider/model to call for report writing. Kept
#         as separate constants so switching provider later doesn't
#         require touching call sites, only this config.
# User configurable: Yes

AI_API_KEY_ENV_VAR = "WEBSCAN_AI_API_KEY"
# Used by: modules/ai/report_writer.py (future)
# Reason: Name of the environment variable holding the API key. The
#         key itself is never stored in this file or in source
#         control.
# User configurable: Yes

AI_MAX_TOKENS = 1024
AI_TEMPERATURE = 0.3
AI_REQUEST_TIMEOUT = 30
# Used by: modules/ai/report_writer.py (future)
# Reason: MAX_TOKENS caps response length/cost per finding write-up;
#         a low TEMPERATURE keeps report wording factual and
#         consistent rather than creative; REQUEST_TIMEOUT prevents
#         report generation from hanging if the API is slow.
# User configurable: Yes

AI_ALLOWED_TASKS = (
    "executive_summary",
    "finding_explanation",
    "remediation_suggestion",
)
# Used by: modules/ai/report_writer.py (future)
# Reason: Explicit allow-list of what the LLM is permitted to do.
#         Deliberately does NOT include "vulnerability_detection" or
#         "severity_scoring" — those stay fully deterministic and
#         code-driven, matching the project's design decision that
#         the AI only improves report writing after findings are
#         already confirmed by the detectors.
# User configurable: Yes, but removing entries is safer than adding
#         new ones without also updating the detectors/report writer
#         to match.


# ======================================================================
# 14. NETWORK / RATE-LIMIT SAFETY NET
# ======================================================================

GLOBAL_MAX_REQUESTS_PER_SCAN = 5000
# Used by: modules/web/crawler.py, modules/analysis/* detectors,
#          scanner/scan_manager.py
# Reason: Absolute ceiling on total HTTP requests for a single scan
#         run, counted across crawling and fuzzing combined. Acts as
#         a last-resort circuit breaker independent of
#         CRAWL_MAX_PAGES/MAX_PAYLOADS_PER_PARAMETER, in case those
#         combine into an unexpectedly large total.
# User configurable: Yes

RATE_LIMIT_REQUESTS_PER_SECOND = 10
# Used by: modules/web/crawler.py, modules/analysis/* detectors
# Reason: Caps outgoing request rate regardless of CRAWL_CONCURRENCY /
#         FUZZ_CONCURRENCY, to avoid overwhelming a target (especially
#         relevant for a resource-limited lab VM like the DVWA/Juice
#         Shop setup).
# User configurable: Yes